trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:

  imageNameClient: 'mern-app-client'
  imageNameServer: 'mern-app-server'
 
stages:
- stage: Build
  displayName: Build Docker Images
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Build and Push Client Docker Image
      inputs:
        
        repository: $(imageNameClient)
        command: buildAndPush
        Dockerfile: '**/client.dockerfile'
        tags: |
          $(Build.BuildId)

    - task: Docker@2
      displayName: Build and Push Server Docker Image
      inputs:
        
        repository: $(imageNameServer)
        command: buildAndPush
        Dockerfile: '**/server.dockerfile'
        tags: |
          $(Build.BuildId)
